### ISSUE TITLE
Interfere with nvim-cmp

### ISSUE THREAD

**Issue by salastro** [skywind3000/vim-auto-popmenu#11]
Hello,

I wanted to use both [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) (for LSP) and `vim-auto-popmenu` (for quick stuff), but they often interrupt each other. I think a possible hack would be enabling `cmp` only for LSP files and `auto-popmenu` for all files except LSP files. However, I do not know of a way to enable `auto-popmenu` for **all files except**. There is only the `*` to match all. I have tried `autocmd FileType python :ApcDisable` and `autocmd BufEnter *.py :ApcDisable`, neither of which worked. The best I can currently do is to manually type `:ApcDisable` every time I enter LSP file. I hope it is possible to somehow fix this.

Thanks for the time.

**Comment by skywind3000** [comment]
Disable auto-popmenu by default, and manually enable it for certain file types by autocmd.

**Comment by salastro** [comment]
I hoped there was a way to automate it, but that's okay I guess.
