### ISSUE TITLE
setlocal infercase 这个功能c/cpp不好用

### ISSUE THREAD

**Issue by Angluca** [skywind3000/vim-auto-popmenu#14]
写代码都会打开ignorecase, 这样小写也可以匹配看到该字符的宏和函数, 方便选择
但用到这个infercase后选择字符串, 所有的字都变成小写了, 还以为这是函数, 结果是宏应该全大写的, 导致c里编译出错,
建议加个选项g:xxx 个人喜好看是否要用这个功能, infercase 感觉不大适合 区分大小写的语言
______________
不过这个设置很适合nim语言, 全可以变小写编译, 
看来用c这些语言关掉ignorecase就好

**Comment by skywind3000** [comment]
我完全没有设置过这个，你搞错了吧？
