### ISSUE TITLE
backspace can't remove char after the latest YCM update.

### ISSUE THREAD

**Issue by roachsinai** [skywind3000/vim-auto-popmenu#2]
![bs](https://user-images.githubusercontent.com/9500049/79693864-b1a4cd00-829f-11ea-997e-44c80f9f6684.gif)

**Comment by roachsinai** [comment]
In above git, I trigger `BS` the result is like `TAB` in some degree, not delete a char.

**Comment by skywind3000** [comment]
disable ycm for certain buffer.

**Comment by roachsinai** [comment]
Works, thanks a lot!
