### ISSUE TITLE
completion popup stops working with "set hidden"

### ISSUE THREAD

**Issue by plt3** [skywind3000/vim-auto-popmenu#5]
Hi, I really like the idea of this plugin, especially for easy comfort while working on remote servers (especially since I can just copy the code into a .vimrc and use it directly). However, while trying it out, I noticed quite a problematic bug that seems to only appear when using `set hidden` in my .vimrc. Basically, when I open a file and type things in insert mode, the plugin works as expected. Then, when I open another file with `:e somefile.txt` and type in that file, it still works. However, if I go back to the first file I was editing (usually with `<C-^>`), and then type a word that should trigger completion, no completion popup appears. I have to press the tab key to get the completion menu. This is unfortunate, because if I switch back to the second buffer open, the completion works as expected. It only seems to break when opening up a new buffer and going back to an older one, and needless to say, I only have the issue when `hidden` is set in my .vimrc.

Here is the minimum needed .vimrc file to reproduce this bug:

```vimL
set hidden

let g:apc_enable_ft = {'*':1}

" don't select the first item.
set completeopt=menu,menuone,noselect

" suppress annoy messages.
set shortmess+=c

call plug#begin('~/.vim/plugged')

Plug 'skywind3000/vim-auto-popmenu'

call plug#end()
```

I have this same problem on the normal macOS version of Vim 8.2 and on the huge version of Vim 8.1 on Debian 10. I tried both installing the plugin using vim-plug as in the example above and just copying the source code into my .vimrc, but no luck with either. I would love to see this fixed, as I would make great use of this plugin otherwise!

Thanks

**Comment by skywind3000** [comment]
I will inspect that ASAP, before that, could you please try:

    :ApcEnable

when the problem happens, and feed me back.

**Comment by skywind3000** [comment]
fixed in https://github.com/skywind3000/vim-auto-popmenu/commit/9236ed71aaf3633be9af5a4d78eb0ade9f66f27f
